# Generated by Django 6.1.1 on 2026-10-06 19:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profile',
            name='profile_targets_nonnegative',
        ),
        migrations.AddField(
            model_name='profile',
            name='initial_carbohydrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('initial_calories__gte', 0), ('initial_carbohydrate__gte', 0), ('initial_fat__gte', 0), ('initial_protein__gte', 0)), name='profile_targets_nonnegative'),
        ),
    ]
