# Generated by Django 6.1.1 on 2026-10-06 18:56

import django.db.models.constraints
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=100)),
                ('title_ar', models.CharField(max_length=100)),
                ('description_en', models.CharField(max_length=250)),
                ('description_ar', models.CharField(max_length=250)),
                ('logged_days_required', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xp_total', models.PositiveBigIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NutritionDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_date', models.DateField()),
                ('target_calories', models.DecimalField(decimal_places=2, max_digits=9)),
                ('target_protein_g', models.DecimalField(decimal_places=2, max_digits=9)),
                ('target_fat_g', models.DecimalField(decimal_places=2, max_digits=9)),
                ('meal_sequence', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-local_date'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('position', models.PositiveIntegerField()),
                ('entry_mode', models.CharField(choices=[('quick', 'Quick'), ('itemized', 'Itemized')], max_length=12)),
                ('food_notes', models.TextField(blank=True)),
                ('quick_calories', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('quick_protein_g', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('quick_fat_g', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('nutrition_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.nutritionday')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLogReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_awarded', models.PositiveIntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nutrition_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nutrition.nutritionday')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=200)),
                ('fingerprint', models.CharField(max_length=64)),
                ('response', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='nutrition_unique_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField()),
                ('calories', models.DecimalField(decimal_places=2, max_digits=9)),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fat_g', models.DecimalField(decimal_places=2, max_digits=9)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.meal')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'constraints': [models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('meal', 'position'), name='nutrition_item_position'), models.CheckConstraint(condition=models.Q(('calories__gte', 0), ('fat_g__gte', 0), ('protein_g__gte', 0)), name='nutrition_positive_items')],
            },
        ),
        migrations.AddConstraint(
            model_name='nutritionday',
            constraint=models.UniqueConstraint(fields=('user', 'local_date'), name='nutrition_unique_day'),
        ),
        migrations.AddConstraint(
            model_name='nutritionday',
            constraint=models.CheckConstraint(condition=models.Q(('target_calories__gte', 0), ('target_fat_g__gte', 0), ('target_protein_g__gte', 0)), name='nutrition_positive_targets'),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('nutrition_day', 'position'), name='nutrition_meal_position'),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_mode', 'quick'), ('quick_calories__gte', 0), ('quick_calories__isnull', False), ('quick_fat_g__gte', 0), ('quick_fat_g__isnull', False), ('quick_protein_g__gte', 0), ('quick_protein_g__isnull', False)), models.Q(('entry_mode', 'itemized'), ('quick_calories__isnull', True), ('quick_fat_g__isnull', True), ('quick_protein_g__isnull', True)), _connector='OR'), name='nutrition_meal_mode'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='nutrition_unique_achievement'),
        ),
    ]
