# Generated by Django 6.1.1 on 2026-10-06 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meal',
            name='nutrition_meal_mode',
        ),
        migrations.RemoveConstraint(
            model_name='mealitem',
            name='nutrition_positive_items',
        ),
        migrations.RemoveConstraint(
            model_name='nutritionday',
            name='nutrition_positive_targets',
        ),
        migrations.AddField(
            model_name='meal',
            name='quick_carbohydrate_g',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='carbohydrate_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='nutritionday',
            name='target_carbohydrate_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.RunSQL("UPDATE nutrition_meal SET quick_carbohydrate_g = 0 WHERE entry_mode = 'quick'", migrations.RunSQL.noop),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_mode', 'quick'), ('quick_calories__gte', 0), ('quick_calories__isnull', False), ('quick_carbohydrate_g__gte', 0), ('quick_carbohydrate_g__isnull', False), ('quick_fat_g__gte', 0), ('quick_fat_g__isnull', False), ('quick_protein_g__gte', 0), ('quick_protein_g__isnull', False)), models.Q(('entry_mode', 'itemized'), ('quick_calories__isnull', True), ('quick_carbohydrate_g__isnull', True), ('quick_fat_g__isnull', True), ('quick_protein_g__isnull', True)), _connector='OR'), name='nutrition_meal_mode'),
        ),
        migrations.AddConstraint(
            model_name='mealitem',
            constraint=models.CheckConstraint(condition=models.Q(('calories__gte', 0), ('carbohydrate_g__gte', 0), ('fat_g__gte', 0), ('protein_g__gte', 0)), name='nutrition_positive_items'),
        ),
        migrations.AddConstraint(
            model_name='nutritionday',
            constraint=models.CheckConstraint(condition=models.Q(('target_calories__gte', 0), ('target_carbohydrate_g__gte', 0), ('target_fat_g__gte', 0), ('target_protein_g__gte', 0)), name='nutrition_positive_targets'),
        ),
    ]
