# Generated by Django 6.1.1 on 2026-10-07 07:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_remove_meal_nutrition_meal_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='amount_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='carbs_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='serving_amount_snapshot_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('saved_food', 'Saved food')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='SavedFood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('serving_amount_g', models.DecimalField(decimal_places=2, max_digits=9)),
                ('calories_per_serving', models.DecimalField(decimal_places=2, max_digits=9)),
                ('protein_g_per_serving', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fat_g_per_serving', models.DecimalField(decimal_places=2, max_digits=9)),
                ('carbs_g_per_serving', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='mealitem',
            name='saved_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_items', to='nutrition.savedfood'),
        ),
        migrations.AddConstraint(
            model_name='savedfood',
            constraint=models.CheckConstraint(condition=models.Q(('calories_per_serving__gte', 0), ('fat_g_per_serving__gte', 0), ('protein_g_per_serving__gte', 0), ('serving_amount_g__gt', 0)), name='saved_food_positive_serving'),
        ),
    ]
