# Generated by Django 6.1.1 on 2026-10-07 20:52

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderDailyBudget',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('sent', 'Sent'), ('rejected', 'Rejected'), ('unknown', 'Unknown'), ('skipped', 'Skipped')], default='claimed', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'week_start'), name='one_weekly_reminder_per_user')],
            },
        ),
        migrations.CreateModel(
            name='ReminderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('weekday', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)])),
                ('local_time', models.TimeField(default=datetime.time(9, 0))),
                ('include_photos', models.BooleanField(default=True)),
                ('confirmed_email', models.EmailField(blank=True, max_length=254)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_nonce', models.UUIDField(default=uuid.uuid4)),
                ('unsubscribe_nonce', models.UUIDField(default=uuid.uuid4)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('schedule_timezone', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('weekday__lte', 6)), name='reminder_valid_weekday')],
            },
        ),
    ]
