# Generated by Django 6.1.1 on 2026-10-06 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('ready_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_key', models.CharField(max_length=255, unique=True)),
                ('thumbnail_key', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('captured_on', models.DateField()),
                ('position', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='progress.weeklyweight')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('weight', 'position'), name='unique_photo_week_position')],
            },
        ),
    ]
